// Generated from the circle avatar set. Ids map to /avatars/<id>.png.
// Regenerate rather than hand-edit if the set changes.

export const AVATARS = [
  '01',
  '3ddd-1',
  '3ddd-2',
  '3ddd-3',
  '3ddd-4',
  '3ddd',
  'afterclap-1',
  'afterclap-2',
  'afterclap-3',
  'afterclap-4',
  'afterclap-5',
  'afterclap-6',
  'afterclap-7',
  'afterclap-8',
  'afterclap-9',
  'afterclap',
  'cranks-1',
  'cranks-2',
  'cranks',
  'delivery-boy-1',
  'delivery-boy-2',
  'delivery-boy-3',
  'delivery-boy-4',
  'delivery-boy-5',
  'delivery-boy',
  'e-commerce-1',
  'e-commerce-2',
  'e-commerce',
  'funny-bunny-1',
  'funny-bunny-2',
  'funny-bunny-3',
  'funny-bunny-4',
  'funny-bunny-5',
  'funny-bunny-6',
  'funny-bunny-7',
  'funny-bunny-8',
  'funny-bunny',
  'guacamole-1',
  'guacamole-2',
  'guacamole-3',
  'guacamole',
  'juicy-1',
  'juicy',
  'no-comments-1',
  'no-comments-2',
  'no-comments-3',
  'no-comments',
  'no-comments-3-2',
  'no-comments-4',
  'no-comments-5',
  'no-comments-6',
  'no-comments-7',
  'no-comments-8',
  'no-comments-9',
  'no-gravity-1',
  'no-gravity-2',
  'no-gravity-3',
  'no-gravity',
  'oslo-1',
  'oslo-10',
  'oslo-11',
  'oslo-12',
  'oslo-13',
  'oslo-14',
  'oslo-2',
  'oslo-3',
  'oslo-4',
  'oslo-5',
  'oslo-6',
  'oslo-7',
  'oslo-8',
  'oslo-9',
  'oslo',
  'teamwork-1',
  'teamwork-2',
  'teamwork-3',
  'teamwork-4',
  'teamwork-5',
  'teamwork-6',
  'teamwork-7',
  'teamwork-8',
  'teamwork',
  'upstream-1',
  'upstream-10',
  'upstream-11',
  'upstream-12',
  'upstream-13',
  'upstream-14',
  'upstream-15',
  'upstream-16',
  'upstream-17',
  'upstream-2',
  'upstream-3',
  'upstream-4',
  'upstream-5',
  'upstream-6',
  'upstream-7',
  'upstream-8',
  'upstream-9',
  'upstream',
] as const;

export type AvatarId = (typeof AVATARS)[number];

export function avatarSrc(id: string): string {
  return `/avatars/${id}.png`;
}

/** Guards the value coming off a form before it is stored or rendered. */
export function isValidAvatar(id: string): boolean {
  return (AVATARS as readonly string[]).includes(id);
}
